<?php

/**
 * Implementation of hook_block().
 */
function occupations_save_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Save');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_save();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_save_theme() {
  return array(
           'occupations_save' => array (
                             'template' => 'occupations_save',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_save() {
  $css_path = drupal_get_path('module', 'occupations_save') . "/occupations_save.css";
  drupal_add_css($css_path);

  return theme('occupations_save');
}

