<?php

/**
 * Implementation of hook_block().
 */
function occupations_helpus_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Help Us Learn About You');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_helpus();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_helpus_theme() {
  return array(
           'occupations_helpus' => array (
                             'template' => 'occupations_helpus',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_helpus() {
  $css_path = drupal_get_path('module', 'occupations_helpus') . "/occupations_helpus.css";
  drupal_add_css($css_path);

  return theme('occupations_helpus');
}

