<?php

/**
 * Implementation of hook_block().
 */
function occupations_grid_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Grid');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_grid();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_grid_theme() {
  return array(
           'occupations_grid' => array (
                             'template' => 'occupations_grid',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_grid() {
  $css_path = drupal_get_path('module', 'occupations_grid') . "/occupations_grid.css";
  drupal_add_css($css_path);
  drupal_add_js(drupal_get_path('module', 'occupations_grid') . '/occupations_grid_nb_save.js');

  return theme('occupations_grid');
}

