<?php

/**
 * Implementation of hook_block().
 */
function occupations_search_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Search');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_search();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_search_theme() {
  return array(
           'occupations_search' => array (
                             'template' => 'occupations_search',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_search() {
  $css_path = drupal_get_path('module', 'occupations_search') . "/occupations_search.css";
  drupal_add_css($css_path);

  return theme('occupations_search');
}

