<?php

/**
 * Implementation of hook_block().
 */
function occupations_findwork_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Find Work');
	  $blocks[1]['info'] = t('Post Healthcare Jobs');
      return $blocks;
      break;
/*     case 'view' :
      $block = array();
      $block['content'] = _get_occupations_findwork();
      return $block;
      break;
	  
	   */
	case 'view' :
			$block = array();
			switch ($delta) 
			{
				case 0: // parent
					$block = array(
						'content' => _get_occupations_findwork(),
					);
					
				break;
				case 1: 
					$block = array(
						'subject' => t('Post Healthcare Jobs'), 
						'content' => _get_occupations_findwork_jobs(),
					);
					
				break;							
				default:
			}
			return $block;	  
		break;
  }
}


/**
 * Implementation of menu().
 */
function occupations_findwork_menu() {
	$items = array();
	
  	/* HOME PAGE */
	$items['findwork/findjobs'] = array(
		'title' => 'Post Healthcare Jobs', 
		'page callback' => '_get_occupations_findwork_jobs',
		'access callback' => TRUE,
        'type' => MENU_CALLBACK,
  	);
  		
  	return $items;
}




/**
 * Implementation of hook_theme().
 */
function occupations_findwork_theme() {
  return array(
           'occupations_findwork' => array (
                             'template' => 'occupations_findwork',
                             'arguments' => array(),
                           ),
			'occupations_findwork_jobs' => array ( 
							'template'=>'occupations_findwork_jobs', 
							'arguments'=>array('errors'=>NULL, 
							'vars'=>NULL, 
							'content'=>NULL, 
							'data'=>NULL) ),
         );
}


function _get_occupations_findwork_jobs($type) {

  	return theme('occupations_findwork_jobs', $errors, $vars, $content, $data);
}



function _get_occupations_findwork() {
  $css_path = drupal_get_path('module', 'occupations_findwork') . "/occupations_findwork.css";
  drupal_add_css($css_path);

  return theme('occupations_findwork');
}

