<?php
/**
 * Implementation of hook_block().
 */
function occupations_match_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Education Match');
	  $blocks[1]['info'] = t('VCN Occupations Education Match');
	  
      return $blocks;
      break;
    case 'view' :
      $block = array();
	  switch ($delta) 
		{
      		case 0: // parent
         		$block = array(
   					'subject' => t(''), 
         			'content' => _get_occupations_match(),
         		);
       		break;
			case 1: 
         		$block = array(
   					'subject' => t(''), 
         			'content' => _get_occupations_match_popup(),
         		);
				
       		break;							
        	default:
       	}
      return $block;
      break;
  }
}
/**
 * Implementation of menu().
 */
function occupations_match_menu() {
	$items = array();
	
  	/* Edcuation Match */
	$items['educationmatch'] = array(
		'title' => '', 
		'page callback' => '_get_occupations_match',
		'access callback' => TRUE,
        'type' => MENU_CALLBACK,
  	);
  		
  	/* Edcuation Match Popup */
	$items['educationmatchpopup'] = array(
		'title' => '', 
		'page callback' => '_get_occupations_match_popup',
		'access callback' => TRUE,
        'type' => MENU_CALLBACK,
  	);		

  	return $items;
}

/**
 * Implementation of hook_theme().
 */
function occupations_match_theme() {
  return array(
           'occupations_match' => array ( 'template' => 'occupations_match', 'arguments' => array() ),
		   'occupations_match_popup' => array ( 'template' => 'occupations_match_popup', 'arguments' => array() ),
         );
}

function _get_occupations_match() {
  $css_path = drupal_get_path('module', 'occupations_match') . "/occupations_match.css";
  drupal_add_css($css_path);

  return theme('occupations_match');
}

function _get_occupations_match_popup() {
  $css_path = drupal_get_path('module', 'occupations_match') . "/occupations_match.css";
  drupal_add_css($css_path);

  return theme('occupations_match_popup');
}