<?php

/**
 * Implementation of hook_block().
 */
function occupations_ladder_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations ladder');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_ladder();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_ladder_theme() {
  return array(
           'occupations_ladder' => array (
                             'template' => 'occupations_ladder',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_ladder() {
  $css_path = drupal_get_path('module', 'occupations_ladder') . "/occupations_ladder.css";
  drupal_add_css($css_path);

  return theme('occupations_ladder');
}

