<?php

/**
 * Implementation of hook_block().
 */
function occupations_top10_growthnumber_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Top 10 Occupations by Growth Number');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_top10_growthnumber();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_top10_growthnumber_theme() {
  return array(
           'occupations_top10_growthnumber' => array (
                             'template' => 'occupations_top10_growthnumber',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_top10_growthnumber() {
  $css_path = drupal_get_path('module', 'occupations_top10_growthnumber') . "/occupations_top10_growthnumber.css";
  drupal_add_css($css_path);

  return theme('occupations_top10_growthnumber');
}

