<?php

/**
 * Implementation of hook_block().
 */
function occupations_quiz_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Quiz');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_quiz();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_quiz_theme() {
  return array(
           'occupations_quiz' => array (
                             'template' => 'occupations_quiz',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_quiz() {
  $css_path = drupal_get_path('module', 'occupations_quiz') . "/occupations_quiz.css";
  drupal_add_css($css_path);

  return theme('occupations_quiz');
}

