<p>
			<strong><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"><span style="color: rgb(178, 34, 34);">1.&nbsp; What does VCN-H stand for?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">VCN-H stands for <em>Virtual Career Network-</em></span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"><em>HealthCare.</em></span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"> Healthcare is among the fastest growing fields in the US economy and offers its workers good salaries and great opportunities for advancement.&nbsp;The VCN-H is an &quot;open source, open content&quot; workforce services and online learning delivery platform built and operated by the American Association of Community Colleges (AACC) under a grant from the Employment and Training Administration (ETA) of the United States Department of Labor (DOL). &nbsp;This website was developed to help US workers transition into healthcare careers. </span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">VCN-H</span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"> users can learn about healthcare careers, locate education and training programs, build a robust career portfolio, and search for jobs.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">2. What is the <em>Career Guide</em> and how long does it take to complete?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">There are 5 Steps in the <em>Career Guide</em> process.&nbsp; It is not intended to be completed in one sitting.&nbsp; It has been designed to serve as a kind of &ldquo;virtual&rdquo; Career Counselor with structured processes to guide first time users through the labyrinth of decisions that they must make and actions they must take to make a successful transition into the right healthcare career for them.&nbsp; Sometimes this may involve actions in the &ldquo;real world&rdquo; outside scope and reach of the website.&nbsp; The goal of the </span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">VCN-H</span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"> is to help users understand what actions they need to take and to guide them in making career decisions when such decisions are necessary.&nbsp;</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">3.&nbsp; What&rsquo;s the difference between using the <em>Career Guide</em> and just navigating around the VCN-H on my own?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">The <em>Career Guide</em> helps first time users of the VCN-H navigate the website by using a structured 5-step process to help them (1) choose a career in healthcare, (2) understand what credentials they need for entry into that career, (3) locate an education or training program through which they can attain those credentials, (4) determine whether they can earn college credit to apply toward that completion of that program based on their prior experience or learning, and (5) when ready search for a job. &nbsp;Many individuals use the career guide after they have completed some initial exploration of the VCN-H on their own.&nbsp; Users can switch back and forth seamlessly between the <span style="font-style: italic;">Career Guide</span><em> </em>and navigating through the site on their own.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">4. &nbsp;What is a <em>Career Management Account</em> and why should I create one the VCN-H?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Creating a VCN Career Management Account(CMA) will provide you many benefits.&nbsp; It enables you to save all your education, training and work information together in one place and to access tools that help you to create a resume, draft cover letters, store transcripts and develop a portfolio of your skills. With an account, you can store information about the decisions you make on the VCN-H so that you can come back later if you do not complete the entire process.&nbsp; This might include healthcare occupations that interest you but you have not yet decided if you want to pursue as a career, or a specific job that you might qualify for now, or a school or educational program in which you might want to enroll.&nbsp;&nbsp; It is a convenient and easy place to store your resume, college application, links to key resources, test scores, and more.&nbsp; You can also access social media, such as Facebook or LinkedIn, through your account.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">5. &nbsp;Is data in my CMA account secure?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Yes.&nbsp; Your data is secured and encrypted both at rest and in transit.&nbsp; What this means is that the information about you is encrypted in our database.&nbsp; It is also encrypted when information is transmitted across the network. No one can access it but you.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">6. &nbsp;What is the source of the career data in the VCN-H?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Career data--such as salary, wages, job growth--are drawn from sources in the US Department of Labor&rsquo;s Bureau of Labor and Statistics.&nbsp; The descriptive information in the Occupational Profiles come from many sources, including O*NET, the BLS&rsquo;s Occupational Outlook Handbook, and the American Medical Association&rsquo;s Health Careers Dictionary.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">7.&nbsp; What is the <em>Interest Profiler</em>?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">This profiling tool was developed by the US Department of Labor, and is self-assessment career exploration tool designed to help you discover the type of activities and occupations that are relevant to you based on your interests.&nbsp; It can help you identify and learn about broad interest areas and enable you to explore compatible healthcare careers.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">8. What is the <em>Wish List</em> and what does it do?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">The &ldquo;wish list&rdquo; is a way of saving those things of interest that you may have found while using the website--careers, instructional programs, credentials, jobs, or other items that you wish to save for further investigation. &nbsp;The &ldquo;wish list&rdquo; is retained by the system as long as an individual is actively on the website, but is deleted when the user closes the browser. However, if the user has a VCN-H Career Management Account, the &ldquo;wish list&rdquo; can be saved into their account for use at a later time.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">9. What is a <em>Career Pathway</em>?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">A &ldquo;career pathway&rdquo; is a map that shows the relationship of jobs in the career you have chosen to other related occupations and careers both higher and lower in a career ladder. You can click on any career shown in the Career Pathway diagram to find out more about that career.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">10. What does &ldquo;EL&rdquo; stand for in the C<em>areer Pathway</em> maps?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">EL stands for Entry Level.&nbsp;Most entry level careers require only basic credentials for entry, such as a high school diploma or completion of short duration training that result in a certificate.&nbsp; You may be able to advance your career by obtaining additional credentials.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">11. What is the difference between <em>Get Qualified</em> and Earn C<em>ollege Credit tabs on the Toolbar</em>?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">The &ldquo;get qualified&rdquo; tab is where a user can search for schools offering instructional programs related to the healthcare career they have chosen and the credential they must earn to secure a job in that career. &nbsp;This feature provides access to more than 18,000 courses and training programs from around the country to prepare you for a variety of healthcare careers.&nbsp; The &ldquo;earn college credits&rdquo; tab provides the user with the ability to determine whether they might obtain college credits based on their prior military experiences, their prior work experiences, college courses they may have already taken, and national placement exams.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">12. What is the source of the accredited schools and instructional programs data provided in the <em>Get Qualified</em> feature?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Learning and training program data is provided by a variety of sources including IPEDS, a database maintained by the US Department of Education, and from direct searching of the websites of the individual colleges, universities and training programs featured on this site.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">13. There is a limited number of training and refresher courses available on this site that an individual can take online.&nbsp; Are there plans to increase the number of such offerings?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Yes.&nbsp; We are adding courses all the time.&nbsp; Subsequent versions of the </span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">VCN-H</span></span><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;"> will have additional courses, particularly refresher courses, available.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">14.&nbsp; The VCN-H is an &ldquo;open source and open content&rdquo; application, is there a plan to provide tools to registered external developers?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Yes, one of the key deliverables of the this project is the development of a VCN-H Open Source Registration and Distribution Portal for VCN-H code and the establishment of a VCN-H Open Source Development Community of registered external developers.&nbsp; This portal will serve as the central online repository for managing the distribution and archiving of VCN-H code and VCN-H derived code, and provide a focal point for technical communication and collaboration among interested parties.</span></span></p>
		<p>
			<strong><span style="color: rgb(178, 34, 34);"><span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">15.&nbsp; Information on education programs is very dynamic, every semester colleges and universities change their course offerings. Will VCN-H be able to keep this information fresh as the educational institutions change their programs?</span></span></span></strong></p>
		<p>
			<span style="font-size: 14px;"><span style="font-family: verdana,geneva,sans-serif;">Yes. &nbsp;We are developing and testing tools which will collect, update, and maintain time sensitive information on instructional programs and other dynamic data contained in the VCN-H.</span></span></p>
	</body>