<p><span style="font-size:14px;">The NHSC is a network of more than 17,000 primary health care professionals and sites that serve the most medically underserved regions of the country. To support their service, the NHSC provides clinicians with financial support in the form of <strong><em>loan repayment</em></strong>s and <strong><em>scholarships</em></strong>.</span></p>
<p><span style="font-size:14px;"><strong>Many types of providers are eligible to join the Corps and get <u>loan repayment assistance</u>&nbsp;&nbsp; </strong></span></p>
<p><span style="font-size:14px;">The NHSC supports communities in need by helping primary care providers with loan repayment. We are seeking providers in a range of primary care specialties, including:</span></p>
<ul><li><span style="font-size:14px;">Physicians (MDs or DOs specializing in pediatrics, geriatrics, psychiatry, family or internal medicine, and obstetrics and gynecology)</span></li><li><span style="font-size:14px;">Nurse Practitioners (adult, family, geriatrics, pediatrics, psychiatric, women&rsquo;s health, and certified nurse midwives)</span></li><li><span style="font-size:14px;">Physician Assistants (primary care)</span></li><li><span style="font-size:14px;">Dental professionals (general, pediatric and geriatric dentists and dental hygienists)</span></li><li><span style="font-size:14px;">Mental health professionals (Health service psychologists, Licensed clinical social workers, Marriage and family therapists, and Licensed professional counselors).</span></li></ul>
<p><span style="font-size: 14px;"><strong>Primary care providers who join the Corps receive up to <u>$170,000 in loan repayment</u> for completing a five-year service commitment&nbsp; </strong></span></p>
<p><span style="font-size:14px;">The NHSC offers loan repayment support with an <em>initial award of up to $60,000 for two years of full-time service.</em> After the initial two-year commitment, providers may be eligible to receive additional support in exchange for continued service; <em>up to $170,000 for five years of service</em>. With continued service beyond five years, clinicians may be able to pay off all their student loans.</span></p>
<p><span style="font-size:14px;"><strong>Students pursuing a degree in qualified health professions can receive a <u>scholarship now and serve later&nbsp;</u> </strong></span></p>
<p><span style="font-size:14px;">Scholarships for tuition, fees, a monthly stipend, and other reasonable educational expenses are available for up to four years. Students who receive scholarships can choose their primary care specialty. They then serve at least two years at a NHSC-approved site in a high-need area.</span></p><p><span style="font-size:14px;"><strong>Corps members can <u>choose their service</u> sites from among many options&nbsp; </strong></span></p>
<p><span style="font-size:14px;">Providers who have completed their training apply for work directly with an approved site of their choice. Corps members who received scholarships choose from a listing of approved sites in high need areas. NHSC-approved sites may be urban, rural, frontier communities, Indian reservations, tribal sites, Federal prisons, or with the Division of Immigration Health Services.&nbsp;</span></p>
<p><span style="font-size:14px;"><strong>Corps members <u>earn competitive salaries</u>&nbsp; </strong></span></p><p><span style="font-size:14px;">Corps members negotiate their salaries directly with their service site. Sites are prohibited from paying Corps members less than their similarly qualified non-Corps colleagues.</span></p><p><span style="font-size:14px;"><strong>NHSC support is <u>tax-free</u></strong></span></p>
<p><span style="font-size:14px;">NHSC loan repayments and scholarships (except for monthly stipends) are exempt from Federal income tax.</span></p>
<p><span style="font-size:14px;"><strong><u>Contact Information </u></strong></span></p>
<p><span style="font-size: 14px;">Visit NHSC.hrsa.gov. Call with application questions at 1-800-221-9393 on weekdays.&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;</span></p>
<p><span style="font-size:14px;">Stay connected through Facebook at: <a href="javascript:popit('http://www.facebook.com/NationalHealthServiceCorps')">www.facebook.com/NationalHealthServiceCorps</a>.</span></p>
<p><span style="font-size:14px;">U.S. Department of Health and Human Services, Health Resources and Services Administration, NHSC</span></p>