<?php
// $Id$
/**
 * @file
 * Module for showing related Topic content
 * in a block.  Based off of Mike Reich's
 * Topic Module.
 */

if(!function_exists('connectIt'))
{
function connectIt()
  {
  //extracting database
  $dbpull .= hvcp_get_db_url();
  $tempArr1=explode("/",$dbpull);
  $tempArr2=explode(":",$tempArr1[2]);
  $dbuser=$tempArr2[0];
  $tempArr3=explode("@",$tempArr2[1]);
  $dbpass=$tempArr3[0];
  $dbserver=$tempArr3[1].":3306";
  unset($tempArr1,$tempArr2,$tempArr3);

  //For now, until we get the REST server set up, we'll just pull the data directly from the database
  $connection=mysql_connect($dbserver,$dbuser,$dbpass)
    or die("Error making database connection: ".mysql_error());
  $db=mysql_select_db('hvcp',$connection)
    or die("Error selecting database: ".mysql_error());
  return($connection);
  }
}

/**
 * Implementation of hook_block
 */
function pla_block($op='list',$delta=0,$edit=array())
  {
  switch ($op)
    {
    case "list":
    // This shows the block name of "Previous Learning Assessment" when you list blocks in admin mode
    $blocks[0]['info']=t('Previous Learning Assessment');
    return $blocks;
    break;

    case "view":
    // block title is "Previous Learning Assessment"
    $blocks['subject']=t('Previous Learning Assessment');

    $base_url = base_path();
    $path=$base_url . "/military-credit";

    /**
     * This next section gets the CMA User ID...
     */
    global $user;
    if($user->uid!=0) $userID=$user->uid;
    else
      {
      $userID=session_id();
      if($userID=="")
        {
        $userID=$_COOKIE[session_name()];
        }
      }
    $select="SELECT USER_ID FROM vcn_cma_user WHERE USER_SESSION_ID=\"$userID\"";
    $connection=connectIt();
    $result=mysql_query($select)
      or die("Error getting USER_ID from vcm_cma_user: ".mysql_error());
    mysql_close($connection);
    $row=mysql_fetch_assoc($result);
    extract($row);

    // get the last course for the user in the database
    $select="SELECT MAX(USER_COURSE_ID) AS DB_LAST_COURSE FROM vcn_cma_user_course WHERE USER_ID=\"$USER_ID\" AND MILITARY_YN=\"Y\"";
    $connection=connectIt();
    $result=mysql_query($select)
      or die("Error selecting last user course".mysql_error());
    mysql_close($connection);
    if($row=mysql_fetch_assoc($result)) extract($row);
    else $DB_LAST_COURSE="";

    // set the last extracted courses
    if($DB_LAST_COURSE!="")
      {
      $select="SELECT COURSE_CODE FROM vcn_cma_user_course WHERE USER_COURSE_ID=\"$DB_LAST_COURSE\"";
      $connection=connectIt();
      $result=mysql_query($select)
        or die("Error selecting info from last record: ".mysql_error);
      mysql_close($connection);
      $row=mysql_fetch_assoc($result);
      extract($row);
      }
    else
      {
      $COURSE_CODE="";
      }

    /**
     * section that deletes a posted request
     */
    if(isset($_POST['USER_COURSE_ID']) && $_POST['function']=="delete")
      {
      $USER_COURSE_ID=$_POST['USER_COURSE_ID'];
      $del="DELETE FROM vcn_cma_user_course WHERE USER_COURSE_ID=\"$USER_COURSE_ID\"";
      $connection=connectIt();
      $results=mysql_query($del) or die("error removing record from table: ".mysql_error());
      mysql_close($connection);
      }
    /**
     * end section that deletes Posted request
     */

    /**
     * section that loads the tabbed interface
     */
    drupal_add_css("sites/all/modules/custom/vcn/pla_main/css/pla_supplemental.css");

    include(drupal_get_path('module','pla_main')."/tabs.inc.php");
    $content .= "<div class=\"container-div\">";
    /** end tabbed interface **/


    $content .= "<div class=\"leftSide\">";
    if(!isset($_GET['ace_id'])) {
      $content .= "<h3>College Credit for Military Training and Occupations</h3>";
    
      $content .= "<p>
			      Have you served in the U.S. Armed Services or with the Department of Defense?
			      Your training and military occupational specialty (MOS) may have college credit recommendations
			      from American Council on Education (ACE).
			      <br />
			      <p>
			      <strong>Military Training</strong>
			      <br/><br/>
			      Many colleges and universities recognize your military training when you provide them with
			      an official transcript from your service branch.
			      </p>
			      <p>
			      Look up college credit recommendations from ACE for your military training.
			      </p>";

      $content .= "<form name=\"pla_ajax\" method=\"POST\" action=\"military-credit#results\">";
      $content .= "<p>Select your branch:<br/> ";
      $content .= "<label>\r\n";
      $content .= "<select name=\"branch\">\r\n";
      if(urldecode($_REQUEST['branch'])=="air force")
       $content .= "<option value=\"air force\" selected>Air Force</option>";
      else
       $content .= "<option value=\"air force\">Air Force</option>";
      if(urldecode($_REQUEST['branch'])=="army")
       $content .= "<option value=\"army\" selected>Army</option>";
      else
       $content .= "<option value=\"army\">Army</option>";
      if(urldecode($_REQUEST['branch'])=="coast guard")
       $content .= "<option value=\"coast guard\" selected>Coast Guard</option>";
      else
       $content .= "<option value=\"coast guard\">Coast Guard</option>";
      if(urldecode($_REQUEST['branch'])=="Dept of Defense")
       $content .= "<option value=\"Dept of Defense\" selected>Department of Defense</option>";
      else
       $content .= "<option value=\"Dept of Defense\">Department of Defense</option>";
      if(urldecode($_REQUEST['branch'])=="marine corps")
       $content .= "<option value=\"marine corps\" selected>Marine Corps</option>";
      else
       $content .= "<option value=\"marine corps\">Marine Corps</option>";
      if(urldecode($_REQUEST['branch'])=="navy")
       $content .= "<option value=\"navy\" selected>Navy</option>";
      else
       $content .= "<option value=\"navy\">Navy</option>";
      $content .= "</select></label></p>\r\n";
      $content .= "<p><label for=\"searchVal\">Enter a military course id number, key words, and/or phrases in the title or leave blank to see all courses:</label><br />";
      $content .= "<input type=\"text\" name=\"searchVal\" id=\"searchVal\" value=\"".$_POST['searchVal']."\" size=50/></p>";
      
      $content .= "<input type=\"image\" src=\"$base_url/sites/all/modules/custom/vcn/occupations/ocupations_search/search.png\" value=\"Search\" alt=\"Search\" title=\"Search\" /></p>";
      $content .= "</form>";
      }

    /**
     * Section to insert courses
     */
    if($_POST['save']=="save")
      {
      $ace_id=$_POST['ace_id'];
      $start_date=$_POST['start_date'];
      $end_date=$_POST['end_date'];
      if($COURSE_CODE != $ace_id."|".$start_date."|".$end_date)
        {
        $insert="INSERT INTO vcn_cma_user_course (USER_ID,COURSE_CODE,MILITARY_YN) VALUES (\"$USER_ID\",\"".$ace_id."|".$start_date."|".$end_date."\",\"Y\")";
        $connection=connectIt();
        $result=mysql_query($insert) or die("Error selecting last military course id: ".mysql_error());
        mysql_close($connection);
        }
      }
    /**
     * End section to insert courses
     */

    /**
     * Section added to delete already selected courses
     */
    $query="SELECT USER_COURSE_ID,COURSE_CODE from vcn_cma_user_course WHERE USER_ID=\"$USER_ID\" AND MILITARY_YN=\"Y\"";
    $connection=connectIt();
    $result=mysql_query($query) or die("error selecting military courses: ".mysql_error());
    $lineCount=mysql_num_rows($result);
	
	if(isset($_GET['ace_id']) && !isset($_POST['searchVal']))
      {
      $ace_id=$_GET['ace_id'];
      $start_date=$_GET['start_date'];
      $end_date=$_GET['end_date'];
      $select1="SELECT *
                FROM   vcn_ace_course
                WHERE  ace_id=\"$ace_id\"
                AND    start_date=\"$start_date\"
                AND    end_date=\"$end_date\"";
      $select2="SELECT *
                FROM   vcn_ace_military_course
                WHERE  ace_id=\"$ace_id\"
                AND    start_date=\"$start_date\"
                AND    end_date=\"$end_date\"";
      $select3="SELECT *
                FROM   vcn_ace_course_credit
                WHERE  ace_id=\"$ace_id\"
                AND    start_date=\"$start_date\"
                AND    end_date=\"$end_date\"";
      $select4="SELECT *
                FROM   vcn_ace_course_credit_span
                WHERE  ace_id=\"$ace_id\"
                AND    start_date=\"$start_date\"
                AND    end_date=\"$end_date\"";
      $connection=connectIt();
      $results1=mysql_query($select1)
        or die("Error running $select1: ".mysql_error());
      $results2=mysql_query($select2)
        or die("Error running $select2: ".mysql_error());
      $results3=mysql_query($select3)
        or die("Error running $select3: ".mysql_error());
      $results4=mysql_query($select4)
        or die("Error running $select4: ".mysql_error());
      mysql_close($connection);

      $row1=mysql_fetch_assoc($results1);
      extract($row1);
      $militaryCourses="";
      while($row2=mysql_fetch_assoc($results2))
        {
        extract($row2);
        $militaryCourses .="$course_id, ";
        }
      $militaryCourses = trim($militaryCourses);
      if(strlen($militaryCourses)>0)
        $militaryCourses=substr($militaryCourses,0,-1);
      
      $content .= "<h3>College Credit for Military Training and Occupations Details</h3>";
      
      $content .= "<div class=\"line2\">";
      $content .= "<p>ACE ID: <strong>$ace_id</strong></p>";
      $content .= "<p>Primary Title: <strong>$first_title</strong></p>";
      if($second_title!="" && $second_title!=NULL)
        $content .= "<p>Secondary Title: <strong>$second_title</strong></p>";
      if($militaryCourses!="")
        $content .= "<p>Applicable Military Courses: <strong>$militaryCourses</strong></p>";
      if($objective!="" && $objective!=Null)
        $content .= "<p>Objective: $objective</p>";
      if($instruction!="" && $instruction !=NULL)
        $content .= "<p>Instruction: $instruction</p>";
      if($ref_sequence!="" && $ref_sequence!=NULL)
        {
        $refDate=substr($ref_date,4,2)."/".substr($ref_date,0,4);
        $content .= "<p>Reference: $ref_sequence $refDate see $ref_ace_id</p>";
        }
      if($results3!=NULL)
        {
        $courseCreditDetails="";
        while($row3=mysql_fetch_assoc($results3))
          {
          extract($row3);
          if($course_conjunction!="" && $course_conjunction!=NULL)
            {
            $courseCreditDetails = substr($courseCreditDetails,0,-4);
            $courseCreditDetails .=" $course_conjunction ";
            }
          if($course_preterm!="" && $course_credit!=NULL)
            $courseCreditDetails .= "$course_preterm ";
          $courseCreditDetails .= "$course_credit $course_credit_unit $course_condition $course_credit_midterm $course_subject</p>";
          if($course_postterm!="" && $course_postterm!=NULL)
            {
            $courseCreditDetails = substr($courseCreditDetails,0,-4);
            $courseCreditDetails .= " $course_postterm</p>";
            }
          }
        $content .= "<p>Course Hours: ";
        $content .= "$courseCreditDetails</p>";
        } // end if($results3!=NULL)
      elseif($credit_info!="" && $credit_info!=NULL)
        $content .= "<p>Additional Course Hour Information: $credit_info</p>";
        $content .= "</div>";
        $content .= "<br /><div>";
        $content .= "<form method=\"POST\" action=\"$path\">";
        $content .= "<input type=\"hidden\" name=\"ace_id\" value=\"$ace_id\" />";
        $content .= "<input type=\"hidden\" name=\"start_date\" value=\"$start_date\" />";
        $content .= "<input type=\"hidden\" name=\"end_date\" value=\"$end_date\" />";
        $content .= "<input type=\"hidden\" id=\"save\" name=\"save\" value=\"save\" />";
        
        if (!isset($_GET['view']) || strlen($_GET['view']) == 0) {
        	$content .= "<input type=\"image\" src=\"$base_url/sites/default/files/images/buttons/save-to-my-learning-inventory.png\" alt=\"Save\" title=\"Save\"/>";
        }

        $content .= "&#160;&#160;";
        $content .= "<input type=\"image\" src=\"$base_url/sites/default/files/images/buttons/search_again.jpg\" onclick=\"document.getElementById('save').value='';\" name=\"searchAgain\" value=\"searchAgain\" alt=\"search again\" title=\"Search Again\"/>";
        $content .= "</form>";
        $content .= "</div>";

    } else {
    	$content .= "<p>
	    	<strong>Military Occupations</strong>
	    	<br><br>
	    	Some colleges also award credit for learning you gained through your
	    	military occupational specialty. For credit recommendations for military
	    	occupations, ";
    	
	    $content .= vcn_build_link_window_opener('http://www.militaryguides.acenet.edu/OccupationSearch.asp', 'click here', false);

	    $content .= " to visit ACE's Military Guide Online.
	    	</p>
	    	<p>
	    	<strong>Transcripts</strong>
	    	<br><br>
	    	Your service branch will provide you with a transcript of your training 
	    	and occupational experiences, including those with ACE credit 
	    	recommendations. Click on your service branch to learn how to order a 
	    	transcript:";

	    $content .= vcn_build_link_window_opener('http://aarts.army.mil/', 'Army', false) . ', ' .
				    vcn_build_link_window_opener('https://smart.navy.mil/', 'Navy/Marines', false) . ', ' .
				    vcn_build_link_window_opener('http://www.au.af.mil/au/ccaf/', 'Air Force', false) . ', ' .
				    vcn_build_link_window_opener('http://www.uscg.mil/hq/cgi/active_duty/go_to_college/official_transcript.asp', 'Coast Guard', false) . ', ' .
				    vcn_build_link_window_opener('http://www.dodea.edu/students/transcripts.cfm', 'Department of Defense', false) . ', ' .
				    '</p>';
	    
    } // end if(isset($_GET['ace_id']) && !isset($_POST['searchVal']))
	
    if($lineCount>0 && !isset($_GET['ace_id']))
      {
      $content .= "<p><b>The following courses have been saved:</b></p>";
      $testCount=0;
      while($row=mysql_fetch_assoc($result))
        {
        extract($row);
        $tempArr=explode("|",$COURSE_CODE);
        $tmpAceID=$tempArr[0];
        $tmpStartDate=$tempArr[1];
        $tmpEndDate=$tempArr[2];
        $select2="SELECT first_title,branch FROM vcn_ace_course WHERE ace_id=\"$tmpAceID\" AND start_date=\"$tmpStartDate\" AND end_date=\"$tmpEndDate\"";
        $result2=mysql_query($select2) or die("error extracting military course credits: ".mysql_error());
        while($row2=mysql_fetch_assoc($result2))
          {
          extract($row2);
          if($testCount%2==0)
            $content .= "<div class=\"line1\">";
          else
            $content .= "<div class=\"line2\">";
          $content .= "<div class=\"StepFiveDivStack\">\r\n
                  <form method=\"POST\" action=\"$path\">\r\n";
          $content .= "<span style=\"display:inline-block; vertical-align: middle; width: 90%;\"><div class=\"StepFiveDivColumn1\">\r\n
                  <a href=\"$path?view=y&ace_id=$tmpAceID&start_date=$tmpStartDate&end_date=$tmpEndDate&branch=".str_replace(" ","+",$branch)."\">$first_title</a>\r\n
                </div></span>\r\n
                <div class=\"StepFiveDivColumn2\">\r\n
                  <input type=\"hidden\" name=\"USER_COURSE_ID\" value=\"$USER_COURSE_ID\" />\r\n
                  <input type=\"hidden\" name=\"function\" value=\"delete\" />\r\n
                </div>\r\n
                <div class=\"StepFiveDivColumn3\">\r\n
                  <input type=\"image\" src=\"$base_url/sites/default/files/images/buttons/delete.png\" alt=\"Remove this item from your saved list\" title=\"Remove this item from your saved list\">\r\n
                </div>\r\n";
          $content .= "<br /></form></div></div>\r\n";
          $testCount++;
          }
        }
      }
    mysql_close($connection);
    /**
     * End section to delete selected courses
     */


    if(isset($_POST['searchVal']))
      {
      $connection=connectIt();
      $branch=mysql_real_escape_string($_POST['branch'],$connection);
      $searchVal=mysql_real_escape_string(html_entity_decode($_POST['searchVal']),$connection);
      $searchValArray=explode(" ",$searchVal);
      if(count($searchValArray)==1)
        {
        $select="SELECT *
                 FROM   vcn_ace_course a,vcn_ace_military_course b
                 WHERE  a.ace_id=b.ace_id
                 AND    a.start_date=b.start_date
                 AND    a.end_date=b.end_date
                 AND    a.branch=\"$branch\"
                 AND    (a.first_title LIKE \"%$searchVal%\"
                 OR     a.second_title LIKE \"%$searchVal%\"
                 OR     b.course_id LIKE \"%$searchVal%\")
                 ";
        }
      elseif(count($searchValArray)==0)
        {
        $select="";
        }
      else // count($searchValArray
        {
        $select="SELECT *
                 FROM   vcn_ace_course a,vcn_ace_military_course b
                 WHERE  a.ace_id=b.ace_id
                 AND    a.start_date=b.start_date
                 AND    a.end_date=b.end_date
                 AND    a.branch=\"$branch\"
                 ";
        foreach($searchValArray as $searchItem)
          {
          $select .= "AND    (a.first_title LIKE \"%$searchItem%\"
                      OR     a.second_title LIKE \"%$searchItem%\"
                      OR     b.course_id LIKE \"%$searchItem%\")
                      ";
          }
        }
      if($select!="")
        $connect .= "ORDER BY b.course_id";

      $db=mysql_select_db("hvcp",$connection)
        or die("cannot select \"hvcp\" database: ".mysql_error());
      if($select!="") $results=mysql_query($select)
        or die("Error running select: ".mysql_error());
      mysql_close($connection);

      $content .= "<a name=\"results\"></a>";
      if(mysql_num_rows($results)>0)
        $content .= "<p>Based upon your search parameters, we suggest the following possible matches:</p> <ul>";
      else
        $content .= '<p><strong style="color:red;">No results found. Please try altering your search.</strong></p><ul>';
      while($row=mysql_fetch_assoc($results))
        {
        extract($row);
        if($end_date=="999999") $endDate="Present";
        else $endDate=substr($end_date,4,2)."/".substr($end_date,0,4);
        $startDate=substr($start_date,4,2)."/".substr($start_date,0,4);
        $urlBranch=urlencode($branch);
        $content .= "<li class=\"extra-space\"><a href=\"?ace_id=$ace_id&start_date=$start_date&end_date=$end_date&branch=$urlBranch\">$course_id - $first_title (Course taken between $startDate and $endDate)</a></li>";
        }
      $content .= "</ul>";
    }
    
    
    
    $content .= "<p><b>Hint:</b> Remember that each college determines how your prior learning might apply to a specific degree program.";
	$content .= "</div> <!-- end div container-div -->";
	$content .= "</div><!-- end div leftSide -->";
	
    // set block content to $content
    $blocks['content']=$content;
    return $blocks;
    break;

    } //end switch($op)
  } // end function pla_block