<?php

/**
 * Implementation of hook_block().
 */
function occupations_top10_jobs_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Top 10 Occupations by Jobs');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_top10_jobs();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_top10_jobs_theme() {
  return array(
           'occupations_top10_jobs' => array (
                             'template' => 'occupations_top10_jobs',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_top10_jobs() {
  $css_path = drupal_get_path('module', 'occupations_top10_jobs') . "/occupations_top10_jobs.css";
  drupal_add_css($css_path);

  return theme('occupations_top10_jobs');
}

