<?php

/**
 * Implementation of hook_block().
 */
function occupations_findworkresults_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations Find Work Results');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_findworkresults();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_findworkresults_theme() {
  return array(
           'occupations_findworkresults' => array (
                             'template' => 'occupations_findworkresults',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_findworkresults() {
  $css_path = drupal_get_path('module', 'occupations_findworkresults') . "/occupations_findworkresults.css";
  drupal_add_css($css_path);

  return theme('occupations_findworkresults');
}

