<?php

/**
 * Implementation of hook_block().
 */
function occupations_similar_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Similar Careers');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_similar();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_similar_theme() {
  return array(
           'occupations_similar' => array (
                             'template' => 'occupations_similar',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_similar() {
  $css_path = drupal_get_path('module', 'occupations_similar') . "/occupations_similar.css";
  drupal_add_css($css_path);

  return theme('occupations_similar');
}

