<?php

/**
 * Implementation of hook_block().
 */
function occupations_aboutus_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('VCN Occupations About Us');
      return $blocks;
      break;
    case 'view' :
      $block = array();
      $block['content'] = _get_occupations_aboutus();
      return $block;
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function occupations_aboutus_theme() {
  return array(
           'occupations_aboutus' => array (
                             'template' => 'occupations_aboutus',
                             'arguments' => array(),
                           ),
         );
}

function _get_occupations_aboutus() {
  $css_path = drupal_get_path('module', 'occupations_aboutus') . "/occupations_aboutus.css";
  drupal_add_css($css_path);

  return theme('occupations_aboutus');
}

